<?php

/**
 * Implements hook_theme().
 */
function student_registration_theme() {
  return [
    'admin_notification_email' => [
      'variables' => ['user_data' => NULL],
      'template' => 'admin-notification-email',
    ],
    'user_notification_email' => [
      'variables' => ['user_id' => NULL, 'user_data' => NULL],
      'template' => 'user-notification-email',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function student_registration_mail($key, &$message, $params) {
  switch ($key) {
    case 'admin_notification':
      $message['subject'] = t('New Student Registration');
      $render_array = [
        '#theme' => 'admin_notification_email',
        '#user_data' => $params['user_data'],
      ];
      $message['body'][] = \Drupal::service('renderer')->renderPlain($render_array);
      break;

    case 'user_notification':
      $message['subject'] = t('Welcome to the Student Portal');
      $render_array = [
        '#theme' => 'user_notification_email',
        '#user_id' => $params['user_id'],
        '#user_data' => $params['user_data'],
      ];
      $message['body'][] = \Drupal::service('renderer')->renderPlain($render_array);
      break;
  }
}
